name: Upload metadata

on:
  push:
    branches:
      - master

env:
  S3_URL: ${{ secrets.S3_URL }}
  ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY }}
  SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
  BACKEND_URL: ${{ secrets.BACKEND_URL }}
  BACKEND_TOKEN: ${{ secrets.BACKEND_TOKEN }}
  BUCKET: ${{ vars.S3_BUCKET }}
  R2_URL: ${{ secrets.R2_URL }}
  R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
  R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
  R2_BUCKET: ${{ vars.R2_BUCKET }}
  R2_REGION: ${{ secrets.R2_REGION }}
  FILELIST_URL: ${{ secrets.FILELIST_URL }}
  REGION: ${{ secrets.REGION }}
  BACKUP_URL: ${{ secrets.BACKUP_URL }}
  BACKUP_ACCESS_KEY_ID: ${{ secrets.BACKUP_ACCESS_KEY_ID }}
  BACKUP_SECRET_ACCESS_KEY: ${{ secrets.BACKUP_SECRET_ACCESS_KEY }}
  BACKUP_BUCKET: ${{ secrets.BACKUP_BUCKET }}
  BACKUP_REGION: ${{ secrets.BACKUP_REGION }}

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - id: pdfium
        name: Get pdfium-binaries latest
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          owner: bblanchon
          repo: pdfium-binaries

      - id: check
        name: Get byrdocs-check release
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          owner: byrdocs
          repo: byrdocs-check

      - name: Download release
        run: |
          wget https://github.com/bblanchon/pdfium-binaries/releases/download/${{ steps.pdfium.outputs.release }}/pdfium-linux-x64.tgz
          tar -zxvf pdfium-linux-x64.tgz
          wget https://github.com/byrdocs/byrdocs-check/releases/download/${{ steps.check.outputs.release }}/check-cmt
          wget https://github.com/byrdocs/byrdocs-check/releases/download/${{ steps.check.outputs.release }}/check-pr
          chmod 777 check-cmt
          chmod 777 check-pr

      - name: Check format
        env:
          DIR: ./metadata
        run: |
          ./check-pr
      - name: Upload metadata
        env:
          DIR: ./metadata
        run: |
          ./check-cmt
